import type { ComponentType, SVGProps } from "react";
import {
  Award,
  Boxes,
  ChartColumn,
  Code2,
  Combine,
  Cpu,
  Database,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  Layers,
  LayoutDashboard,
  Link,
  Mail,
  MessageCircle,
  Monitor,
  MousePointer2,
  Palette,
  Rocket,
  Server,
  Shield,
  Smartphone,
  Sparkles,
  Star,
  Target,
  Terminal,
  Trophy,
  Zap,
} from "lucide-react";
import {
  FaGithub,
  FaInstagram,
  FaLinkedin,
  FaWhatsapp,
} from "react-icons/fa";

type IconComponent = ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;

const iconMap: Record<string, IconComponent> = {
  Award,
  Boxes,
  ChartColumn,
  Code2,
  Combine,
  Cpu,
  Database,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  Layers,
  LayoutDashboard,
  Link,
  Mail,
  MessageCircle,
  Monitor,
  MousePointer2,
  Palette,
  Rocket,
  Server,
  Shield,
  Smartphone,
  Sparkles,
  Star,
  Target,
  Terminal,
  Trophy,
  Zap,
  Github: FaGithub,
  Instagram: FaInstagram,
  Linkedin: FaLinkedin,
  Whatsapp: FaWhatsapp,
};

export function getIcon(name?: string | null): IconComponent {
  return iconMap[name ?? ""] ?? Code2;
}